namespace InventoryTools.Logic.Settings.Abstract
{
    public enum SettingSubCategory
    {
        None,
        AutoSave,
        FilterSettings,
        ActiveLists,
        Experimental,
        Fun,
        Hotkeys,
        Highlighting,
        DestinationHighlighting,
        RetainerHighlighting,
        Market,
        ContextMenus,
        Visuals,
        WindowLayout,
        General,
        Subsetting,
        IgnoreEscape,
        SourceGrouping,
        UseGrouping,
        Colours,
        AddItemLocations,
        MarketPricing,
        AmountToRetrieve,
        ItemUnlockStatus,
        SourceInformation,
        UseInformation,
    }
}