name: Automatically PR plogon

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Create pull request
        uses: daemitus/DalamudPluginPR2@master
        with:
          token: ${{ secrets.PAT }}
          plugin_name: InventoryTools
          testing: "[Testing]"
          project_path: InventoryTools
          plugin_owners: Critical_Impact