name: Create D17 PR

on:
  push:
    tags:
      - '*'

env:
  INTERNAL_NAME: InventoryTools
  PLUGIN_NAME: Allagan Tools
  UPDATE_NAME: AT

jobs:
  update-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Extract version and changelog
        id: changelog
        run: |
          VERSION=$(grep -m1 -oP '(?<=## \[)[0-9]+\.[0-9]+\.[0-9]+' ${{ env.INTERNAL_NAME }}/CHANGELOG.md)
          echo "version=1.$VERSION" >> $GITHUB_OUTPUT
          CHANGELOG=$(awk -v ver=$VERSION '/^#+ \[/ { if (p) { exit }; if ($2 == "["ver"]") { p=1; next} } p && NF' ${{ env.INTERNAL_NAME }}/CHANGELOG.md)
          echo "log<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Checkout fork of external repo
        uses: actions/checkout@v4
        with:
          repository: Critical-Impact/DalamudPluginsD17
          fetch-depth: '1'
          path: external
          token: ${{ secrets.PR_PAT }}

      - name: Configure git and create branch
        run: |
          cd external
          git remote add goatcorp https://github.com/goatcorp/DalamudPluginsD17.git
          git fetch goatcorp
          git checkout -b ${{ env.UPDATE_NAME }}-${{ steps.changelog.outputs.version }} goatcorp/main

      - name: Configure git author
        run: |
          cd external
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Update manifest.toml
        run: |
          cd external
          pip install toml
          python - <<EOF
          import toml
          from pathlib import Path
          
          manifest_path = Path("stable/${{ env.INTERNAL_NAME }}/manifest.toml")
          data = toml.load(manifest_path)
          
          # Update commit and changelog
          data["plugin"]["commit"] = "${GITHUB_SHA}"
          data["plugin"]["version"] = "${{ steps.changelog.outputs.version }}"
          data["plugin"]["changelog"] = """${{ steps.changelog.outputs.log }}"""
          
          with manifest_path.open("w") as f:
              toml.dump(data, f)
          EOF
          git add stable/${{ env.INTERNAL_NAME }}/manifest.toml
          git commit -m "${{ env.PLUGIN_NAME }} ${{ steps.changelog.outputs.version }}"          

      - name: Push branch to fork
        run: |
          cd external
          git push origin -f HEAD:${{ env.UPDATE_NAME }}-${{ steps.changelog.outputs.version }}