name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - inventory-scopes

env:
  INTERNAL_NAME: InventoryToolsTesting
  CONFIGURATION: Release
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  download-exd:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve cache
        uses: actions/cache@v4
        with:
          path: exd-data
          # Use the .cachemeta.json file to invalidate the cache when the data changes.
          key: exd-files-data-${{hashFiles('exd-data/.cachemeta.json')}}
          restore-keys: |
            exd-files-data-
      - name: Download EXD Files
        uses: WorkingRobot/ffxiv-downloader@v7
        with:
          output-path: exd-data
          regex: '^sqpack\/ffxiv\/0a0000\..+$'
      - name: Debug downloaded EXD files
        run: |
          echo "Workspace contents:"
          ls -la "${{ github.workspace }}"
          echo "Home directory contents:"
          ls -la $HOME
          echo "Any .ffxiv directory:"
          ls -la $HOME/.ffxiv